config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :feedbacks
  end  
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  get 'static_pages/services'

  resources :orders, only: [:index, :show, :create, :destroy]

  post 'static_pages/thank_you'
  post 'payments/create'

  root 'static_pages#landing_page'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
  validates :user, presence: true
  validates :post, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

	def create
        debugger
		@post = Post.find(params[:post_id])
		@feedback = @post.feedbacks.new(feedback_params)
   		@feedback.user = current_user
    	respond_to do |format|
    		if @feedback.save
    			format.html { redirect_to @post, notice: 'Comment was created successfully.' }
        		format.json { render :show, status: :created, location: @post }
        	else
        	format.html { redirect_to @post, alert: 'Comment was not saved successfully.' }
        	format.json { render json: @feedback.errors, status: :unprocessable_entity }
        end
    end
end


	def destroy
    	@feedback = Feedback.find(params[:id])
    	post = @feedback.post
   		@feedback.destroy
    	redirect_to post 
	end

	private

	def feedback_params
		params.require(:feedback).permit(:user_id, :body)
	end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_feedback_listing.html.erb
<div class="feedback-listing">
  <% @feedbacks.each do |feedback| %>
  <div class="row">
    <% if signed_in? && current_user.admin? %>
    <hr>
    <p>
      <%= feedback.user.first_name %> <small><em><%= "#{time_ago_in_words(feedback.created_at)} ago" %></em></small>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, post_feedback_path(@post, feedback), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
      <p><%= feedback.body %></p>
    <% else %>
      <hr>
      <p>
        <%= feedback.user.first_name %> <small><em><%= "#{time_ago_in_words(feedback.created_at)} ago" %></em></small>
      </p>
      <p><%= feedback.body %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/feedbacks/_new_feedback.html.erb
<% if signed_in? %>
  <h4>Add a comment:</h4> <p>
  <%= bootstrap_form_for([@post, @post.feedbacks.build]) do |f| %> </p>
    <div class="field">
      <%= f.text_area :body, style: "resize:none", rows: "5", cols: "40" %>
    </div>
    <hr>
      <%= f.submit "Submit" %>
  <% end %>
<% end %>